"""Agregar campos de mantenimiento en equipos

Revision ID: 088e6b2953c0
Revises: 
Create Date: 2025-11-01 13:20:11.326071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088e6b2953c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proximo_mantenimiento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('ultimo_mantenimiento', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_column('ultimo_mantenimiento')
        batch_op.drop_column('proximo_mantenimiento')

    # ### end Alembic commands ###
